apiVersion: v1
kind: Pod
metadata:
  name: test-grafana-alert
  namespace: grafana
  labels:
    app: nht-loki-demo 
spec:
  containers:
  - name: myapp
    image: ubuntu:22.04
    resources:
      limits:
        memory: "300Mi"
        cpu: "500m"
    command: ["/bin/bash", "-c"]
    args: ["while true; do echo Printing-a-dummy-alert; sleep 15; done"]